package org.apache.jsp.page.branch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class branchlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/page/branch/../head/head.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");

String varname = (String) request.getParameter("varname");

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>机动车网上交通安全宣传教育监管平台</title>\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/pagination/pagination.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/pagination/jquery.pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/autoscreen.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/index.js\"></script>\r\n");
      out.write("<!-- the mousewheel plugin -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/jquery.mousewheel.js\"></script>\r\n");
      out.write("<!-- the jScrollPane script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/jquery.jscrollpane.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/scroll-startstop.events.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://app.mapabc.com/apis?t=javascriptmap&v=3.1.1&key=3dc46b2cab503188ce5ce86c2c22bbcbc9bce56a5f0737ce79ddb1cd63c3b337a315cc8c1e8fe18c\"></script>\r\n");
      out.write("<script src=\"page/js/map/basic.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"page/js/map/typeAhead2.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function nTabs(thisObj,Num){\r\n");
      out.write("if(thisObj.className == \"active\")return;\r\n");
      out.write("var tabObj = thisObj.parentNode.id;\r\n");
      out.write("var tabList = document.getElementById(tabObj).getElementsByTagName(\"li\");\r\n");
      out.write("for(i=0; i <tabList.length; i++)\r\n");
      out.write("{\r\n");
      out.write("  if (i == Num)\r\n");
      out.write("  {\r\n");
      out.write("   thisObj.className = \"active\"; \r\n");
      out.write("      document.getElementById(tabObj+\"_Content\"+i).style.display = \"block\";\r\n");
      out.write("  }else{\r\n");
      out.write("   tabList[i].className = \"normal\"; \r\n");
      out.write("   document.getElementById(tabObj+\"_Content\"+i).style.display = \"none\";\r\n");
      out.write("  }\r\n");
      out.write("} \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function nTabs1(thisObj,Num,id){\r\n");
      out.write("if($(thisObj).attr('class') == \"active1\") return;\r\n");
      out.write("var tabObj = $(thisObj).parent().attr('id');\r\n");
      out.write("\r\n");
      out.write("$('#'+tabObj+' li').each(function(){\r\n");
      out.write("\t$(this).removeClass(); \r\n");
      out.write("\t$(this).addClass(\"normal1\"); \r\n");
      out.write("});\r\n");
      out.write("$(\"div[id^=\"+tabObj+\"_Content1]\").css(\"display\",\"none\");\r\n");
      out.write("\r\n");
      out.write("$(\"#\"+tabObj+\"_Content1\"+Num).css(\"display\",\"block\");\r\n");
      out.write("$(thisObj).removeClass(); \r\n");
      out.write("$(thisObj).addClass(\"active1\"); \r\n");
      out.write("if(id !=0)\r\n");
      out.write(" initMap1(id);\r\n");
      out.write(" else \r\n");
      out.write("  initMap();\r\n");
      out.write("//if(thisObj.className == \"active1\")return;\r\n");
      out.write("//var tabObj = thisObj.parentNode.id;\r\n");
      out.write("//var tabList = document.getElementById(tabObj).getElementsByTagName(\"li\");\r\n");
      out.write("//for(i=0; i <tabList.length; i++)\r\n");
      out.write("//{\r\n");
      out.write("//  if (i == Num)\r\n");
      out.write("//  {\r\n");
      out.write("//   thisObj.className = \"active1\"; \r\n");
      out.write("//      document.getElementById(tabObj+\"_Content1\"+i).style.display = \"block\";\r\n");
      out.write("//  }else{\r\n");
      out.write("//   tabList[i].className = \"normal1\"; \r\n");
      out.write("//   document.getElementById(tabObj+\"_Content1\"+i).style.display = \"none\";\r\n");
      out.write("//  }\r\n");
      out.write("//} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function nTabs2(thisObj,Num){\r\n");
      out.write("alert(thisObj);\r\n");
      out.write("if(thisObj.className == \"active2\")return;\r\n");
      out.write("var tabObj = thisObj.parentNode.id;\r\n");
      out.write("var tabList = document.getElementById(tabObj).getElementsByTagName(\"li\");\r\n");
      out.write("for(i=0; i <tabList.length; i++)\r\n");
      out.write("{\r\n");
      out.write("  if (i == Num)\r\n");
      out.write("  {\r\n");
      out.write("   thisObj.className = \"active2\"; \r\n");
      out.write("      document.getElementById(tabObj+\"_Content2\"+i).style.display = \"block\";\r\n");
      out.write("  }else{\r\n");
      out.write("   tabList[i].className = \"normal2\"; \r\n");
      out.write("   document.getElementById(tabObj+\"_Content2\"+i).style.display = \"none\";\r\n");
      out.write("  }\r\n");
      out.write("} \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//$(document).ready(function() {\r\n");
      out.write("// var oMoveBox = $(\"#col_box\"), oArr = $(\"#arrow\"), maxL = 185;\r\n");
      out.write("// oArr.click(function(){\r\n");
      out.write("//  oMoveBox.animate({\"height\":\"-=\"+maxL},185,function(){\r\n");
      out.write("//   maxL = -maxL;\r\n");
      out.write("//  // $(\"#arrow\").html(maxL<0 ? \"﹀\" : \"︿\");\r\n");
      out.write("// $(\"#arrow\").html(maxL<0 ? \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\\\"></img>\" : \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk01.png\\\"></img>\");\r\n");
      out.write("//  })\r\n");
      out.write("// });\r\n");
      out.write("//});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write(" var oMoveBox = $(\"#col_box\"), oArr = $(\"#arrow\"), maxL = 185;\r\n");
      out.write(" oArr.click(function(){\r\n");
      out.write("  oMoveBox.animate({\"height\":\"-=\"+maxL},185,function(){\r\n");
      out.write("   maxL = -maxL;\r\n");
      out.write("  $(\"#arrow\").html(maxL<0 ? \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\\\"></img>\" : \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk01.png\\\"></img>\");\r\n");
      out.write("  })\r\n");
      out.write(" });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"top\" id=\"box\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"col_box\">\r\n");
      out.write("<table width=\"100%\" height=\"108\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"float:left\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t<span class=\"padding-left \"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index_view.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/logo.png\" class=\"autoheight\" style=\"width:508px;height:104px;\" /></a></span>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td rowspan=\"2\" align=\"right\" valign=\"bottom\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/logo_img1.png\"/>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 15px;width:100%\">\r\n");
      out.write("\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t    <!--首页-->\r\n");
      out.write("\t\t\t    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index_view.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav11.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t    <!--交通法规-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/rule_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav01.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--宣教中心-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/edu_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav02.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--基本信息-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/driver_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav03.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--违法查询-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/ruleIllegal_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav04.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--快速处理点-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/branch_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav05.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--安全提醒-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/safeNotice_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav06.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--会议通知-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/meetNotice_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav07.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--问题互动-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/interchange_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav08.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--微博微信-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/micromessage_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav09.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--后台管理-->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<!--<div id=\"arrow\">︿</div>-->\r\n");
      out.write("<div id=\"arrow\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\"> </img></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>");
      out.write(" \r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("     \r\n");
      out.write("    <div class=\"nTab1\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 标题开始 -->\r\n");
      out.write("    <div class=\"TabTitle1\">\r\n");
      out.write("    <div class=\"jt_h3 pos\"><span class=\"left main_left\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/icon05.png\" align=\"absmiddle\" />&nbsp;&nbsp;快速处理点</span><span class=\"gb\"><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/close.png\" width=\"10\" height=\"10\" /></a></span>\r\n");
      out.write("      <ul id=\"myTab10\">\r\n");
      out.write("        <li class=\"active1\" onmouseover=\"nTabs1(this,0,0);\">列表</li>\r\n");
      out.write("        <li class=\"normal1\" onmouseover=\"nTabs1(this,1,0);\">地图</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 内容开始 -->\r\n");
      out.write("    <div class=\"TabContentny1\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- 列表 -->\r\n");
      out.write("   <div id=\"myTab10_Content10\">\r\n");
      out.write("       \t \r\n");
      out.write("    <div style=\"height:auto!important;min-height:450px;height:450px;\">\r\n");
      out.write("      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-bottom:0px;\">\r\n");
      out.write("         <tr style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/cl_list_top.gif) repeat-x;\">\r\n");
      out.write("           <td width=\"40%\" height=\"27\" align=\"center\"><strong>快速处理点</strong></td>\r\n");
      out.write("           <td width=\"40%\" height=\"27\" align=\"center\"><strong>地址</strong></td>\r\n");
      out.write("           <td width=\"10%\" height=\"27\" align=\"center\"><strong>电话</strong></td>\r\n");
      out.write("           <td width=\"10%\" align=\"center\"><strong>详情</strong></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"branchlisthtml\"></table>\r\n");
      out.write("     </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"clear\"></div>\r\n");
      out.write("   <div class=\"sabrosus\"><div id='Pagination' class=\"pagination\"></div></div>\r\n");
      out.write("   <div id=\"TB_overlayBG\"></div>\r\n");
      out.write("   <div class=\"boxt\" style=\"display:none\">\r\n");
      out.write("\t\t<h2>快速处理点<a href=\"#\" class=\"close\">关闭</a></h2>\r\n");
      out.write("\t\t<div class=\"mainlist\">\r\n");
      out.write("\t\t <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("           <tr>\r\n");
      out.write("\t\t\t    <td width=\"15%\">快速处理点：</td>\r\n");
      out.write("\t\t\t    <td width=\"35%\" id=\"branchName\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"15%\">联系电话：</td>\r\n");
      out.write("\t\t\t    <td width=\"35%\" id=\"branchPhone\">&nbsp;</td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("     \t\t<td width=\"15%\">地址：</td>\r\n");
      out.write("    \t\t<td width=\"35%\" colspan=\"3\" id=\"branchAddress\">&nbsp;</td>\r\n");
      out.write("  \t\t  </tr>\r\n");
      out.write(" \t\t  <tr>\r\n");
      out.write("   \t\t\t <td>经度：</td>\r\n");
      out.write("    \t\t <td id=\"lng\">&nbsp;</td>\r\n");
      out.write("    \t\t <td>纬度：</td>\r\n");
      out.write("    \t\t <td id=\"lat\">&nbsp;</td>\r\n");
      out.write(" \t\t  </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\t\t\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 地图 -->\r\n");
      out.write("<div id=\"myTab10_Content11\" class=\"none\" style=\"height:550px;\">\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 内容结束 -->\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"color:#2a81c4; text-align:center\">版权所有：机动车网上交通安全宣传教育监控平台&nbsp;&nbsp;技术支持：浙江网泽</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tmap_basic_init(11,'myTab10_Content11',120.2,30.3,false);\r\n");
      out.write("\tvar optInit = getOptionsFromForm();\r\n");
      out.write("\t$(\"#Pagination\").pagination(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(", optInit);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".close\").click(function(){\r\n");
      out.write("\t\t$(\"#TB_overlayBG\").css(\"display\",\"none\");//通过id属性绑定\r\n");
      out.write("\t\t$(\".boxt\").css(\"display\",\"none\");//通过class属性绑定\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//分页回调函数\r\n");
      out.write("function pageselectCallback(page_index, jq){\r\n");
      out.write("\t// Get number of elements per pagionation page from form\r\n");
      out.write("\tpage_index = page_index + 1;\r\n");
      out.write("\tvar newcontent = '';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getBranchDatedetailList.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'currentpage='+page_index+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("\t\t\tif(re.size > 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor(var i =0 ; i<re.branchlists.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t  // newcontent +='<tr><td width=\"40%\" height=\"36\" align=\"center\" class=\"branch\"  lng=\"'+re.branchlists[i].lng+'\" lat=\"'+re.branchlists[i].lat+'\" branchAddress=\"'+re.branchlists[i].branchAddress+'\">'+'<a href=\"#\" onclick=\"pageselectCallback('+re.branchlists[i].id+')\">'+re.branchlists[i].branchName+'</a>' + '</td><td align=\"center\" width=\"40%\">'+re.branchlists[i].branchAddress+'</td><td width=\"10%\" align=\"center\">'+re.branchlists[i].branchPhone+'</td><td align=\"center\" width=\"10%\"><a href=\"#\" onclick=\"detailinfo('+re.branchlists[i].id+')\">详情</a></td></tr>';\r\n");
      out.write("\t\t\t\t   newcontent +='<tr><td width=\"40%\" height=\"36\" align=\"center\" class=\"branch\"  lng=\"'+re.branchlists[i].lng+'\" lat=\"'+re.branchlists[i].lat+'\" branchAddress=\"'+re.branchlists[i].branchAddress+'\" branchPhone=\"'+re.branchlists[i].branchPhone+'\" id=\"'+re.branchlists[i].id+'\">'+'<a href=\"#\" onclick=\"nTabs1($(\\'.normal1\\'),1,'+re.branchlists[i].id+')\">'+re.branchlists[i].branchName+'</a>' + '</td><td align=\"center\" width=\"40%\">'+re.branchlists[i].branchAddress+'</td><td width=\"10%\" align=\"center\">'+re.branchlists[i].branchPhone+'</td><td align=\"center\" width=\"10%\"><a href=\"#\" onclick=\"detailinfo('+re.branchlists[i].id+')\">详情</a></td></tr>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#branchlisthtml').html(newcontent);\r\n");
      out.write("\t\t\t//删除兴趣点\r\n");
      out.write("\t\t\tmap_basic_dellayer('m');\r\n");
      out.write("\t\t\t//添加兴趣点\r\n");
      out.write("\t\t\tinitMap();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t// Replace old content with new content\r\n");
      out.write("\t\r\n");
      out.write("\t// Prevent click eventpropagation\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// The form contains fields for many pagiantion optiosn so you can\r\n");
      out.write("// quickly see the resuluts of the different options.\r\n");
      out.write("// This function creates an option object for the pagination function.\r\n");
      out.write("// This will be be unnecessary in your application where you just set\r\n");
      out.write("// the options once.\r\n");
      out.write("function getOptionsFromForm(){\r\n");
      out.write("\tvar opt = {callback: pageselectCallback};\r\n");
      out.write("\t// Collect options from the text fields - the fields are named like their option counterparts\r\n");
      out.write("\t//\"Previous\" label\r\n");
      out.write("\topt.prev_text = '上一页';\r\n");
      out.write("\t//\"Next\" label\r\n");
      out.write("\topt.next_text = '下一页';\r\n");
      out.write("\t//Number of pagination links shown\r\n");
      out.write("\topt.num_display_entries = '3';\r\n");
      out.write("\t//Number of items per page\r\n");
      out.write("\topt.items_per_page = '15';\r\n");
      out.write("\t// Avoid html injections in this demo\r\n");
      out.write("\tvar htmlspecialchars ={ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\"};\r\n");
      out.write("\t$.each(htmlspecialchars, function(k,v){\r\n");
      out.write("\t\topt.prev_text = opt.prev_text.replace(k,v);\r\n");
      out.write("\t\topt.next_text = opt.next_text.replace(k,v);\r\n");
      out.write("\t})\r\n");
      out.write("\treturn opt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//点击详情的具体信息，采用模态窗口的方式显示信息\r\n");
      out.write("function detailinfo(id)\r\n");
      out.write("{\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getBranchDateinfo.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'branchid='+id+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("  \t\t\t$('#branchName').html('&nbsp;'+re.branchName);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 姓名\r\n");
      out.write("\t\t\t$('#branchAddress').html('&nbsp;'+re.branchAddress);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 地址\r\n");
      out.write("\t\t\t$('#branchPhone').html('&nbsp;'+re.branchPhone);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 经度\r\n");
      out.write("\t\t\t$('#lng').html('&nbsp;'+(re.lng == 'null'?'':re.lng));\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 纬度\r\n");
      out.write("\t\t\t$('#lat').html('&nbsp;'+(re.lat == 'null'?'':re.lat));\r\n");
      out.write("\r\n");
      out.write("\t\t\tbindshow();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\treturn;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//详情信息的模态窗口\r\n");
      out.write("function bindshow()\r\n");
      out.write("{\r\n");
      out.write("\t$(\"#TB_overlayBG\").css({\r\n");
      out.write("\t\tdisplay:\"block\",height:$(document).height()\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".boxt\").css({\r\n");
      out.write("\t\tleft:($(\"body\").width()-$(\".boxt\").width())/2-20+\"px\",\r\n");
      out.write("\t\ttop:($(window).height()-$(\".boxt\").height())/3+$(window).scrollTop()+\"px\",\r\n");
      out.write("\t\tdisplay:\"block\"\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//兴趣点\r\n");
      out.write("function initMap()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\t$('.branch').each(function(){\r\n");
      out.write("\t\t//alert(obj.attr('branchAddress'));\r\n");
      out.write("\t\tvar obj = $(this);\r\n");
      out.write("\t\tif(obj.attr('lng') != '' && obj.attr('lat') != '' && obj.attr('lng') != 'null' && obj.attr('lat') != 'null')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\taddmark(obj.attr('lng'),obj.attr('lat'));\r\n");
      out.write("\t\t\t//alert(obj.attr('lng'));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\taddmarkbysearch(obj.attr('id'),obj.attr('branchAddress'),obj.text(),obj.attr('branchPhone'),0);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//兴趣点\r\n");
      out.write("function initMap1(id)\r\n");
      out.write("{\r\n");
      out.write("map_basic_mapObj.clearMap();//清除地图上的覆盖物\r\n");
      out.write("\t$('.branch').each(function(){\r\n");
      out.write("\tvar obj = $(this);\r\n");
      out.write("\t\t//alert(obj.attr('branchAddress'));\r\n");
      out.write("\t\tif(id == obj.attr('id')){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(obj.attr('lng') != '' && obj.attr('lat') != '' && obj.attr('lng') != 'null' && obj.attr('lat') != 'null')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\taddmark(obj.attr('lng'),obj.attr('lat'));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\taddmarkbysearch(obj.attr('id'),obj.attr('branchAddress'),obj.text(),obj.attr('branchPhone'),id);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//在高德地图上查找具体的位置\r\n");
      out.write("function addmarkbysearch(id,keyword,name,phone,indexid)\r\n");
      out.write("{  \r\n");
      out.write("\t//alert(keyword);\r\n");
      out.write("\tvar poiSearchOption = {\r\n");
      out.write("\t\tsrctype:\"POI\",//数据来源\r\n");
      out.write("\t\ttype:\"\",//数据类别\r\n");
      out.write("\t\tnumber:1,//每页数量，默认10\r\n");
      out.write("\t\tbatch:1,//请求页数，默认1\r\n");
      out.write("\t\trange:3000,\t//查询范围，默认3000米\r\n");
      out.write("\t\text:\"\"//扩展字段\r\n");
      out.write("\t\t};\r\n");
      out.write("\tvar poiSearch = new MMap.PoiSearch(poiSearchOption);\r\n");
      out.write("\tpoiSearch.byKeywords(keyword,\"0571\", function(data){\r\n");
      out.write("\t\t//alert(data.count);\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar opt ={}; \r\n");
      out.write("\t\topt.image=\"http://code.mapabc.com/images/lan_1.png\"; \r\n");
      out.write("\t\topt.size=new MMap.Size(16,20); \r\n");
      out.write("\t\topt.imageOffset=new MMap.Pixel(0,18); \r\n");
      out.write("\t\ticon = new MMap.Icon(opt);//构造自定义MMap.Icon对象\r\n");
      out.write("\t\tif(data.status == 'E0')\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t//alert(data.list[0].x);\r\n");
      out.write("\t\t\tvar marker;\r\n");
      out.write("\t\t\tif(indexid ==0){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmarker = new MMap.Marker({id:\"m\"+data.list[0].x,position:new MMap.LngLat(data.list[0].x ,data.list[0].y),content:'<image width=\"16px;\" height=\"20px;\" src=\"http://code.mapabc.com/images/lan_1.png\"> '\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}) \r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmarker = new MMap.Marker({id:\"m\"+data.list[0].x,position:new MMap.LngLat(data.list[0].x ,data.list[0].y),content:'<image width=\"16px;\" height=\"20px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/map/spot_2.png\"> '\t\t\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//自定义构造MMap.Marker对象\r\n");
      out.write("\t\t\t//marker2 = new MMap.Marker({id:\"o\",position:new MMap.LngLat(120.126548 ,30.323654),content:'<image width=\"16px;\" height=\"20px;\" src=\"http://code.mapabc.com/images/lan_1.png\" title=\"'+name+'\"> '}) //自定义构造MMap.Marker对象\r\n");
      out.write("\t\t\tmap_basic_mapObj.addOverlays(marker); //加载覆盖物\r\n");
      out.write("\t\t\t//map_basic_mapObj.addOverlays(marker2); \r\n");
      out.write("\t\t\tmap_basic_mapObj.setCenter(new MMap.LngLat(data.list[0].x ,data.list[0].y));\r\n");
      out.write("\t\t\tvar inforwindow = new MMap.InfoWindow({\r\n");
      out.write("\t\t\t\t\t\tlevel:13,//初始地图视野级别\r\n");
      out.write("\t\t\t\t\t\tisCustom:true,\r\n");
      out.write("\t\t\t\t\t\tcontent:InfoWindow1(0,id,name,keyword,name,phone),\r\n");
      out.write("\t\t\t\t\t\tautoMove:true ,\r\n");
      out.write("\t\t\t\t\t\tsize:new MMap.Size(200,10),\r\n");
      out.write("\t\t\t\t\t\toffset:new MMap.Pixel(-75,-100) // 靠下，第一个数控制左右方向，第二数控制上下方向\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t//鼠标移动到地图点上时显示详细信息\r\n");
      out.write("\t\t\t map_basic_mapObj.bind(marker,\"mouseover\",function(e){\r\n");
      out.write("\t\t\t\tinforwindow.open(map_basic_mapObj,marker.getPosition());   \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//鼠标离开点时详细信息窗口关闭\r\n");
      out.write("\t\t\tmap_basic_mapObj.bind(marker,\"mouseout\",function(e){\r\n");
      out.write("\t\t\t\tinforwindow.close(map_basic_mapObj,marker.getPosition());   \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tif(indexid !==0) {\r\n");
      out.write("\t\t\t\tinforwindow.open(map_basic_mapObj,marker.getPosition());   \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//在高德地图上显示具体的位置\r\n");
      out.write("function addmark(x,y)\r\n");
      out.write("{\r\n");
      out.write("\t\talert(x+y);\r\n");
      out.write("\t\tvar opt ={}; \r\n");
      out.write("\t\topt.image=\"http://code.mapabc.com/images/lan_1.png\"; \r\n");
      out.write("\t\topt.size=new MMap.Size(16,20); \r\n");
      out.write("\t\topt.imageOffset=new MMap.Pixel(0,-18); \r\n");
      out.write("\t\ticon = new MMap.Icon(opt);//构造自定义MMap.Icon对象\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar marker;\r\n");
      out.write("\t\tmarker = new MMap.Marker({id:\"m\",position:new MMap.LngLat(x ,y),content:'<image width=\"16px;\" height=\"20px;\" src=\"http://code.mapabc.com/images/lan_1.png\">'}) //自定义构造MMap.Marker对象\r\n");
      out.write("\t\tmap_basic_mapObj.addOverlays(marker); //加载覆盖物\r\n");
      out.write("\r\n");
      out.write("\t\tmap_basic_mapObj.setCenter(new MMap.LngLat(x ,y));\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//快速处理点窗口\r\n");
      out.write("function InfoWindow1(flag,id,title,address,name,phone){\r\n");
      out.write("    var info_style_icon = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/map/info_01.png\";\r\n");
      out.write("\tvar content = \"\";\r\n");
      out.write("\tif(address.length>13){\r\n");
      out.write("\t\taddress = address.substring(0,13)+\"...\";\r\n");
      out.write("\t}\r\n");
      out.write("\tcontent += \"&nbsp;&nbsp;快速处理点：\" + name + \"<br/>\";\r\n");
      out.write("\tcontent += \"&nbsp;&nbsp;地址：\" + address + \"<br/>\"; \r\n");
      out.write("\tcontent += \"&nbsp;&nbsp;电话：\" + phone + \"<br/>\"; \r\n");
      out.write("\treturn infoWindow_style(flag,id,title,content,info_style_icon);\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
