package org.apache.jsp.page.driver;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class driverlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/page/driver/../head/head.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>机动车网上交通安全宣传教育监管平台</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/pagination/pagination.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/pagination/jquery.pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/autoscreen.js\"></script>\r\n");
      out.write("<!-- the mousewheel plugin -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/jquery.mousewheel.js\"></script>\r\n");
      out.write("<!-- the jScrollPane script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/jquery.jscrollpane.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/scroll-startstop.events.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write(" var oMoveBox = $(\"#col_box\"), oArr = $(\"#arrow\"), maxL = 185;\r\n");
      out.write(" oArr.click(function(){\r\n");
      out.write("  oMoveBox.animate({\"height\":\"-=\"+maxL},185,function(){\r\n");
      out.write("   maxL = -maxL;\r\n");
      out.write("  $(\"#arrow\").html(maxL<0 ? \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\\\"></img>\" : \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk01.png\\\"></img>\");\r\n");
      out.write("  })\r\n");
      out.write(" });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"top\" id=\"box\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"col_box\">\r\n");
      out.write("<table width=\"100%\" height=\"108\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"float:left\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t<span class=\"padding-left \"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index_view.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/logo.png\" class=\"autoheight\" style=\"width:508px;height:104px;\" /></a></span>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td rowspan=\"2\" align=\"right\" valign=\"bottom\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/logo_img1.png\"/>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 15px;width:100%\">\r\n");
      out.write("\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t    <!--首页-->\r\n");
      out.write("\t\t\t    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index_view.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav11.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t    <!--交通法规-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/rule_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav01.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--宣教中心-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/edu_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav02.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--基本信息-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/driver_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav03.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--违法查询-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/ruleIllegal_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav04.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--快速处理点-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/branch_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav05.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--安全提醒-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/safeNotice_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav06.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--会议通知-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/meetNotice_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav07.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--问题互动-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/interchange_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav08.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--微博微信-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/micromessage_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav09.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--后台管理-->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<!--<div id=\"arrow\">︿</div>-->\r\n");
      out.write("<div id=\"arrow\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\"> </img></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>");
      out.write(" \r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("\t<div class=\"nTab3\">\r\n");
      out.write("\t<div class=\"TabTitle3\">\r\n");
      out.write("    <div class=\"jt_h3 pos\">\r\n");
      out.write("\t\t<span class=\"left main_left\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/icon03.png\"  align=\"absmiddle\" />&nbsp;&nbsp;基本信息</span>\r\n");
      out.write("\t\t<span class=\"gb\"><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/close.png\" width=\"10\" height=\"10\" /></a></span>\r\n");
      out.write("\t\t<ul id=\"myTab30\">\r\n");
      out.write("\t\t\t<li class=\"active3\" onmouseover=\"nTabs3(this,0);\">基本信息</li>\r\n");
      out.write("\t\t\t<li class=\"normal3\" onmouseover=\"nTabs3(this,1);\">车辆管理</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    <div class=\"TabContentny3\"><!-- 内容开始 -->\r\n");
      out.write("   \t<div id=\"myTab30_Content30\"><!-- 列表 -->\r\n");
      out.write("    <div class=\"box_nr1\">\r\n");
      out.write("    <div class=\"jbxx_nr1\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-bottom:0px;\">\r\n");
      out.write("\t\t\t<tr style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/jb_list_top.gif) repeat-x;\">\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"26\" align=\"center\"><strong>姓名</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"27\" align=\"center\"><strong>年龄</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"27\" align=\"center\"><strong>性别</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"27\" align=\"center\"><strong>所属公司</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"12%\" height=\"27\" align=\"center\"><strong>身份证号码</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"12%\" height=\"27\" align=\"center\"><strong>年审日期</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"10%\" height=\"27\" align=\"center\"><strong>电话</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"12%\" height=\"27\" align=\"center\"><strong>有效日期</strong></td>\r\n");
      out.write("\t\t\t\t<td height=\"27\" align=\"center\"><strong>地址</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" align=\"center\"><strong>操作</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>  \r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"driverlisthtml\"></table>  \r\n");
      out.write("\t</div>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("    <div class=\"sabrosus\">\r\n");
      out.write("\t\t<div id='Pagination' class=\"pagination\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"TB_overlayBG\"></div>\r\n");
      out.write("\t<div class=\"boxt\" style=\"display:none\">\r\n");
      out.write("\t\t<h2>基本信息<a href=\"#\" class=\"close\">关闭</a></h2>\r\n");
      out.write("\t\t<div class=\"mainlist\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"10%\">姓名：</td>\r\n");
      out.write("\t\t\t\t<td width=\"25%\" id=\"name\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"10%\">年龄：</td>\r\n");
      out.write("\t\t\t\t<td width=\"25%\" id=\"age\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"10%\">性别：</td>\r\n");
      out.write("\t\t\t\t<td id=\"sex\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>身份证：</td>\r\n");
      out.write("\t\t\t\t<td id=\"identitycard\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td>电话</td>\r\n");
      out.write("\t\t\t\t<td id=\"phone\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>地址：</td>\r\n");
      out.write("\t\t\t\t<td id=\"address\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>准驾车型</td>\r\n");
      out.write("\t\t\t\t<td id=\"cartype\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>年审日期</td>\r\n");
      out.write("\t\t\t\t<td id=\"certificationtime\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td >所属公司</td>\r\n");
      out.write("\t\t\t\t<td id=\"dwid\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<td >有效日期</td>\r\n");
      out.write("\t\t\t\t<td id=\"validtime\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 车辆管理 -->\r\n");
      out.write("<div class=\"TabContentny3\"><!-- 内容开始 -->\r\n");
      out.write("   \t<div id=\"myTab30_Content30\"><!-- 列表 -->\r\n");
      out.write("    <div class=\"box_nr1\">\r\n");
      out.write("    <div class=\"jbxx_nr1\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-bottom:0px;\">\r\n");
      out.write("\t\t\t<tr style=\"background:url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/jb_list_top.gif) repeat-x;\">\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"26\" align=\"center\"><strong>车牌号</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"27\" align=\"center\"><strong>常用驾驶员</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"27\" align=\"center\"><strong>驾驶员电话</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"12%\" height=\"27\" align=\"center\"><strong>车辆类型</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"12%\" height=\"27\" align=\"center\"><strong>生产厂家</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"10%\" height=\"27\" align=\"center\"><strong>所属公司</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"12%\" height=\"27\" align=\"center\"><strong>起始时间</strong></td>\r\n");
      out.write("\t\t\t\t<td height=\"27\" height=\"27\" align=\"center\"><strong>结束时间</strong></td>\r\n");
      out.write("\t\t\t\t<td width=\"8%\" height=\"27\" align=\"center\"><strong>操作</strong></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>  \r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"carlisthtml\"></table>  \r\n");
      out.write("\t</div>\r\n");
      out.write("    <div class=\"clear\"></div>\r\n");
      out.write("    <div class=\"sabrosus\">\r\n");
      out.write("\t\t<div id='Pagination2' class=\"pagination\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"TB_overlayBG2\"></div>\r\n");
      out.write("\t<div class=\"boxt2\" style=\"display:none\">\r\n");
      out.write("\t\t<h2>车辆管理<a href=\"#\" class=\"close\">关闭</a></h2>\r\n");
      out.write("\t\t<div class=\"mainlist2\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"10%\">车牌号：</td>\r\n");
      out.write("\t\t\t\t<td width=\"25%\" id=\"busLicPlate\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"10%\">常用驾驶员：</td>\r\n");
      out.write("\t\t\t\t<td width=\"25%\" id=\"driver1\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td width=\"10%\">驾驶员电话：</td>\r\n");
      out.write("\t\t\t\t<td id=\"phone1\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>车辆类型：</td>\r\n");
      out.write("\t\t\t\t<td id=\"busType\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>生产厂家</td>\r\n");
      out.write("\t\t\t\t<td id=\"manufacturer\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>所属公司：</td>\r\n");
      out.write("\t\t\t\t<td id=\"comname\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>登记证书</td>\r\n");
      out.write("\t\t\t\t<td id=\"regCode\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td>起始时间</td>\r\n");
      out.write("\t\t\t\t<td id=\"regStartTime\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td >结束时间</td>\r\n");
      out.write("\t\t\t\t<td id=\"regEndTime\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"clear\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("  \t<div style=\"color:#2a81c4; text-align:center\">版权所有：机动车网上交通安全宣传教育监控平台&nbsp;&nbsp;技术支持：浙江网泽</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t//基本信息\r\n");
      out.write("\tvar optInit = getOptionsFromForm();\r\n");
      out.write("\t$(\"#Pagination\").pagination(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(", optInit);\r\n");
      out.write("\t$(\".close\").click(function(){\r\n");
      out.write("\t\t$(\"#TB_overlayBG\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\".boxt\").css(\"display\",\"none\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t//车辆管理\r\n");
      out.write("\tvar optInit2 = getOptionsFromForm2();\r\n");
      out.write("\t$(\"#Pagination2\").pagination(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(", optInit2);\r\n");
      out.write("\t$(\".close\").click(function(){\r\n");
      out.write("\t\t$(\"#TB_overlayBG2\").css(\"display\",\"none\");\r\n");
      out.write("\t\t$(\".boxt2\").css(\"display\",\"none\");\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//基本信息、车辆管理\r\n");
      out.write("function nTabs3(thisObj, Num) {\r\n");
      out.write("\t\r\n");
      out.write("\tif (thisObj.className == \"active3\")\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\tvar tabObj = thisObj.parentNode.id;\r\n");
      out.write("\t\r\n");
      out.write("\tvar tabList = document.getElementById(tabObj)\r\n");
      out.write("\t\t\t.getElementsByTagName(\"li\");\r\n");
      out.write("\tfor (i = 0; i < tabList.length; i++) {\r\n");
      out.write("\t\tvar width = $(thisObj).css('width');\r\n");
      out.write("\t\tif (i == Num) {\r\n");
      out.write("\t\t\t$(thisObj).removeClass('normal3');\r\n");
      out.write("\t\t\t$(thisObj).removeClass('active3');\r\n");
      out.write("\t\t\t$(thisObj).addClass('active3');\r\n");
      out.write("\t\t\tdocument.getElementById(tabObj + \"_Content3\" + i).style.display = \"block\";\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(tabList[i]).removeClass('normal3');\r\n");
      out.write("\t\t\t$(tabList[i]).removeClass('active3');\r\n");
      out.write("\t\t\t$(tabList[i]).addClass('normal3');\r\n");
      out.write("\t\t\tdocument.getElementById(tabObj + \"_Content3\" + i).style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//分页回调函数-基本信息\r\n");
      out.write("function pageselectCallback(page_index, jq){\r\n");
      out.write("\t// Get number of elements per pagionation page from form\r\n");
      out.write("\tpage_index = page_index + 1;\r\n");
      out.write("\tvar newcontent = '';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getDriverDatedrilist.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'currentpage='+page_index+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t\t\tif(re.size > 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor(var i =0 ; i<re.drivers.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t newcontent +='<tr><td width=\"8%\" height=\"36\" align=\"left\"\">'+re.drivers[i].name+'</td><td align=\"left\"\" width=\"8%\">'+re.drivers[i].age+'</td><td width=\"8%\" align=\"left\"\">'+re.drivers[i].sex+'</td><td width=\"8%\" align=\"left\"\">'+re.drivers[i].dwid+'</td><td align=\"left\"\" width=\"12%\"><p>'+re.drivers[i].identitycard+'</p></td><td width=\"12%\" height=\"36\" align=\"left\"\">'+re.drivers[i].certificationtime+'</td><td width=\"10%\" height=\"36\" align=\"left\"\">'+re.drivers[i].phone+'</td><td width=\"12%\" height=\"36\" align=\"left\"\">'+re.drivers[i].validtime+'</td><td>'+re.drivers[i].address+'</td><td width=\"8%\" align=\"left\"\"><a href=\"#\" onclick=\"detailinfo('+re.drivers[i].id+');\">查询</a></td></tr>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#driverlisthtml').html(newcontent);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t// Replace old content with new content\r\n");
      out.write("\t\r\n");
      out.write("\t// Prevent click eventpropagation\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//分页回调函数-车辆管理\r\n");
      out.write("function pageselectCallback2(page_index, jq){\r\n");
      out.write("\t// Get number of elements per pagionation page from form\r\n");
      out.write("\tpage_index = page_index + 1;\r\n");
      out.write("\tvar newcontent = '';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getCarDatacarList.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'currentpage='+page_index+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re = eval('('+data+')');\r\n");
      out.write("\t\t\tif(re.size > 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor(var i =0 ; i<re.cars.length;i++)\r\n");
      out.write("\t\t\t\t{\t\r\n");
      out.write("\t\t\t\t\tvar dv1 = re.cars[i].driver1;\r\n");
      out.write("\t\t\t\t\tif(dv1 == \"null\"){dv1 = \"\";}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar ph1 = re.cars[i].phone1;\r\n");
      out.write("\t\t\t\t\tif(ph1 == \"null\"){ph1 = \"\";}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar mft = re.cars[i].manufacturer;\r\n");
      out.write("\t\t\t\t\tif(mft == \"null\"){mft = \"\";}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar cmn = re.cars[i].comname;\r\n");
      out.write("\t\t\t\t\tif(cmn == \"null\"){cmn = \"\";}\r\n");
      out.write("\t\t\t\t\t newcontent +='<tr><td width=\"8%\" height=\"36\" align=\"left\">'+re.cars[i].busLicPlate+'</td><td align=\"left\"\" width=\"8%\">'+dv1+'</td><td width=\"8%\" align=\"left\"\">'+ph1+'</td><td align=\"left\"\" width=\"12%\"><p>'+re.cars[i].busType+'</p></td><td width=\"12%\" height=\"36\" align=\"left\"\">'+mft+'</td><td width=\"10%\" height=\"36\" align=\"left\"\">'+cmn+'</td><td width=\"12%\" height=\"36\" align=\"left\"\">'+re.cars[i].regStartTime+'</td><td>'+re.cars[i].regEndTime+'</td><td width=\"8%\" align=\"left\"\"><a href=\"#\" onclick=\"detailinfo2('+re.cars[i].carid+');\">详情</a></td></tr>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#carlisthtml').html(newcontent);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t// Replace old content with new content\r\n");
      out.write("\t\r\n");
      out.write("\t// Prevent click eventpropagation\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// The form contains fields for many pagiantion optiosn so you can\r\n");
      out.write("// quickly see the resuluts of the different options.\r\n");
      out.write("// This function creates an option object for the pagination function.\r\n");
      out.write("// This will be be unnecessary in your application where you just set\r\n");
      out.write("// the options once.\r\n");
      out.write("function getOptionsFromForm(){\r\n");
      out.write("\tvar opt = {callback: pageselectCallback};\r\n");
      out.write("\t// Collect options from the text fields - the fields are named like their option counterparts\r\n");
      out.write("\t//\"Previous\" label\r\n");
      out.write("\topt.prev_text = '上一页';\r\n");
      out.write("\t//\"Next\" label\r\n");
      out.write("\topt.next_text = '下一页';\r\n");
      out.write("\t//Number of pagination links shown\r\n");
      out.write("\topt.num_display_entries = '3';\r\n");
      out.write("\t//Number of items per page\r\n");
      out.write("\topt.items_per_page = '15';\r\n");
      out.write("\t// Avoid html injections in this demo\r\n");
      out.write("\tvar htmlspecialchars ={ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\"};\r\n");
      out.write("\t$.each(htmlspecialchars, function(k,v){\r\n");
      out.write("\t\topt.prev_text = opt.prev_text.replace(k,v);\r\n");
      out.write("\t\topt.next_text = opt.next_text.replace(k,v);\r\n");
      out.write("\t})\r\n");
      out.write("\treturn opt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getOptionsFromForm2(){\r\n");
      out.write("\tvar opt = {callback: pageselectCallback2};\r\n");
      out.write("\t// Collect options from the text fields - the fields are named like their option counterparts\r\n");
      out.write("\t//\"Previous\" label\r\n");
      out.write("\topt.prev_text = '上一页';\r\n");
      out.write("\t//\"Next\" label\r\n");
      out.write("\topt.next_text = '下一页';\r\n");
      out.write("\t//Number of pagination links shown\r\n");
      out.write("\topt.num_display_entries = '3';\r\n");
      out.write("\t//Number of items per page\r\n");
      out.write("\topt.items_per_page = '15';\r\n");
      out.write("\t// Avoid html injections in this demo\r\n");
      out.write("\tvar htmlspecialchars ={ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\"};\r\n");
      out.write("\t$.each(htmlspecialchars, function(k,v){\r\n");
      out.write("\t\topt.prev_text = opt.prev_text.replace(k,v);\r\n");
      out.write("\t\topt.next_text = opt.next_text.replace(k,v);\r\n");
      out.write("\t})\r\n");
      out.write("\treturn opt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//车辆管理\r\n");
      out.write("function detailinfo2(id)\r\n");
      out.write("{\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getCarDatainfo.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'carid='+id+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re = eval('('+data+')');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar dv1 = re.driver1;\r\n");
      out.write("\t\t\tif(dv1 == \"null\"){dv1 = \"\";}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ph1 = re.phone1;\r\n");
      out.write("\t\t\tif(ph1 == \"null\"){ph1 = \"\";}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar mft = re.manufacturer;\r\n");
      out.write("\t\t\tif(mft == \"null\"){mft = \"\";}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar cmn = re.comname;\r\n");
      out.write("\t\t\tif(cmn == \"null\"){cmn = \"\";}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//车牌号\r\n");
      out.write("  \t\t\t$('#busLicPlate').html('&nbsp;'+re.busLicPlate);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 常用驾驶员\r\n");
      out.write("\t\t\t$('#driver1').html('&nbsp;'+dv1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 驾驶员电话\r\n");
      out.write("\t\t\t$('#phone1').html('&nbsp;'+ph1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 车辆类型\r\n");
      out.write("\t\t\t$('#busType').html('&nbsp;'+re.busType);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 生产厂家\r\n");
      out.write("\t\t\t$('#manufacturer').html('&nbsp;'+mft);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 所属公司\r\n");
      out.write("\t\t\t$('#comname').html('&nbsp;'+cmn);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 登记证书\r\n");
      out.write("\t\t\t$('#regCode').html('&nbsp;'+re.regCode);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 起始时间\r\n");
      out.write("\t\t\t$('#regStartTime').html('&nbsp;'+re.regStartTime);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 结束时间\r\n");
      out.write("            $('#regEndTime').html('&nbsp;'+re.regEndTime);\r\n");
      out.write("\t\t\tbindshow2();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\treturn;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function detailinfo(id)\r\n");
      out.write("{\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getDriverDateinfo.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'driverid='+id+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("\t\t//alert(data);\r\n");
      out.write("  \t\t\t$('#phone').html('&nbsp;'+re.phone);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 姓名\r\n");
      out.write("\t\t\t$('#name').html('&nbsp;'+re.name);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 地址\r\n");
      out.write("\t\t\t$('#address').html('&nbsp;'+re.address);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 身份证号\r\n");
      out.write("\t\t\t$('#identitycard').html('&nbsp;'+re.identitycard);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 性别\r\n");
      out.write("\t\t\t$('#sex').html('&nbsp;'+re.sex);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 所属公司\r\n");
      out.write("\t\t\t$('#dwid').html('&nbsp;'+re.dwid);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 准驾车型\r\n");
      out.write("\t\t\t$('#cartype').html('&nbsp;'+re.cartype);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 有效日期\r\n");
      out.write("\t\t\t$('#validtime').html('&nbsp;'+re.validtime);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 年审日期\r\n");
      out.write("\t\t\t$('#certificationtime').html('&nbsp;'+re.certificationtime);\r\n");
      out.write("\r\n");
      out.write("            $('#age').html('&nbsp;'+re.age);\r\n");
      out.write("\t\t\tbindshow();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\treturn;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function bindshow()\r\n");
      out.write("{\r\n");
      out.write("\t$(\"#TB_overlayBG\").css({\r\n");
      out.write("\t\tdisplay:\"block\",height:$(document).height()\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".boxt\").css({\r\n");
      out.write("\t\tleft:($(\"body\").width()-$(\".boxt\").width())/2-20+\"px\",\r\n");
      out.write("\t\ttop:($(window).height()-$(\".boxt\").height())/3+$(window).scrollTop()+33+\"px\",\r\n");
      out.write("\t\tdisplay:\"block\"\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function bindshow2()\r\n");
      out.write("{\r\n");
      out.write("\t$(\"#TB_overlayBG2\").css({\r\n");
      out.write("\t\tdisplay:\"block\",height:$(document).height()\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".boxt2\").css({\r\n");
      out.write("\t\tleft:($(\"body\").width()-$(\".boxt2\").width())/2-20+\"px\",\r\n");
      out.write("\t\ttop:($(window).height()-$(\".boxt2\").height())/3+$(window).scrollTop()+18+\"px\",\r\n");
      out.write("\t\tdisplay:\"block\"\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
