package org.apache.jsp.page.edu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class eduVideolist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/page/edu/../head/head.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>机动车网上交通安全宣传教育监管平台</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 视频模块所需的 -->\r\n");
      out.write("<link href=\"http://vjs.zencdn.net/c/video-js.css\" rel=\"stylesheet\"/>  \r\n");
      out.write("<script src=\"http://vjs.zencdn.net/c/video.js\"></script>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"http://html5shiv.googlecode.com/svn/trunk/html5.js\"></script>\r\n");
      out.write("<script src=\"http://api.html5media.info/1.1.4/html5media.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/css/css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jquery.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/pagination/pagination.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/pagination/jquery.pagination.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/autoscreen.js\"></script>\r\n");
      out.write("<!-- the mousewheel plugin -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/jquery.mousewheel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- the jScrollPane script -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/jquery.jscrollpane.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/jScroll/scroll-startstop.events.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/js/util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function nTabs(thisObj,Num){\r\n");
      out.write("if(thisObj.className == \"active\")return;\r\n");
      out.write("var tabObj = thisObj.parentNode.id;\r\n");
      out.write("var tabList = document.getElementById(tabObj).getElementsByTagName(\"li\");\r\n");
      out.write("for(i=0; i <tabList.length; i++)\r\n");
      out.write("{\r\n");
      out.write("  if (i == Num)\r\n");
      out.write("  {\r\n");
      out.write("   thisObj.className = \"active\"; \r\n");
      out.write("      document.getElementById(tabObj+\"_Content\"+i).style.display = \"block\";\r\n");
      out.write("  }else{\r\n");
      out.write("   tabList[i].className = \"normal\"; \r\n");
      out.write("   document.getElementById(tabObj+\"_Content\"+i).style.display = \"none\";\r\n");
      out.write("  }\r\n");
      out.write("} \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function videomore(eduid)\r\n");
      out.write("{\r\n");
      out.write("\tif(eduid != '')\r\n");
      out.write("\t{\r\n");
      out.write("\t\tlocation.href = 'edu_info.action?eduid='+eduid;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//左边分页回调函数 视频模块\r\n");
      out.write("function pageselectCallback(page_index, jq){\r\n");
      out.write("\t// Get number of elements per pagionation page from form\r\n");
      out.write("\tpage_index = page_index + 1;\r\n");
      out.write("\tvar newcontent = '';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getEduDateedulist.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'currentpage='+page_index+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("\t\t\tif(re.size > 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor(var i =0 ; i<re.eduvideos.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t //alert(re.eduvideos[i].videourl);\r\n");
      out.write("\t\t\t\t\t //\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${video.videoUrl}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("\" frameborder=0 allowfullscreen></iframe>\r\n");
      out.write("\t\t\t\t\t newcontent += '<li><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td width=\"150\" align=\"center\" valign=\"middle\"><img src=\"' + re.eduvideos[i].img +'\" width=\"125\" height=\"80\" /></td><td align=\"left\" valign=\"top\"><p><strong style=\"cursor:pointer;\" onmousemove=this.style.color=\"red\" onmouseout=this.style.color=\"#044885\" onclick=\"loadRuleContent(';\r\n");
      out.write("\t\t\t\t\t newcontent += re.eduvideos[i].id;\r\n");
      out.write("\t\t\t\t\t newcontent +=');\">';\r\n");
      out.write("\t\t\t\t\t newcontent +='&nbsp;&nbsp;&nbsp;点击播放';\r\n");
      out.write("\t\t\t\t\t newcontent +='</strong>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#999999\">';\r\n");
      out.write("\t\t\t\t\t//newcontent +=re.eduvideos[i].content;\r\n");
      out.write("\t\t\t\t\t newcontent +='</font></p><p>';\r\n");
      out.write("\t\t\t\t\t //newcontent +='点播';\r\n");
      out.write("\t\t\t\t\t newcontent +='&nbsp;&nbsp;&nbsp;&nbsp;'+ re.eduvideos[i].content;\r\n");
      out.write("\t\t\t\t\t newcontent +='</p></td></tr></table></li>';\r\n");
      out.write("\t\t\t\t\t if(i==0)\r\n");
      out.write("\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t \tloadRuleContent(re.eduvideos[i].id);\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#edulisthtml').html(newcontent);\r\n");
      out.write("\t\t\t//var lidiv = {'self':'.limit','rate':35};$(document.body).limit(document.documentElement.clientWidth,lidiv);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('ajax error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t// Replace old content with new content\r\n");
      out.write("\t\r\n");
      out.write("\t// Prevent click eventpropagation\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("//右边页面显示栏  视频模块\r\n");
      out.write("function loadRuleContent(id)\r\n");
      out.write("{\r\n");
      out.write("\t\tvar newcontent ='';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getEduDateinfo.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'eduid='+id+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("\t\t\t\t/* newcontent +='<iframe width=100%  class=\"autoheight\" src=\"' + re.videourl +'\" height=\"460\" />';\r\n");
      out.write("\t\t\t\tnewcontent +='<div>'+(re.content == 'null' ? \"暂无详细内容\":re.content)+'</div>'; */\r\n");
      out.write("\t\t\t\tnewcontent +='<video id=\"my_video_1\" class=\"video-js vjs-default-skin\" controls preload=\"auto\" poster=\"\" data-setup=\"{}\" height=\"460\" width=\"800\">'; \r\n");
      out.write("\t\t\t\tnewcontent +='<source src=\"'+re.videourl+'\"type=video/mp4/></video>'; \r\n");
      out.write("\t\t\t\tnewcontent +='<div>'+(re.content == 'null' ? \"暂无详细内容\":re.content)+'</div>';\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$('#contenthtml').html(newcontent);\r\n");
      out.write("\t\t\tautoscroll({'id':'jp-container'});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//左边分页回调函数 图文模块\r\n");
      out.write("function pageselectCallback2(page_index, jq){\r\n");
      out.write("\t// Get number of elements per pagionation page from form\r\n");
      out.write("\tpage_index = page_index + 1;\r\n");
      out.write("\tvar newcontent = '';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getEduDateedulist.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'currentpage='+page_index+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\t\t\tvar re =eval('('+data+')');\r\n");
      out.write("\t\t\tif(re.size > 0)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tfor(var i =0 ; i<re.eduvideos.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t newcontent += '<li><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"><tr><td width=\"150\" align=\"center\" valign=\"middle\"><img src=\"' + re.eduvideos[i].img +'\" width=\"125\" height=\"80\" /></td><td align=\"left\" valign=\"top\"><p><strong style=\"cursor:pointer;\" onclick=\"loadRuleContent2(';\r\n");
      out.write("\t\t\t\t\t newcontent += re.eduvideos[i].id;\r\n");
      out.write("\t\t\t\t\t newcontent +=');\">';\r\n");
      out.write("\t\t\t\t\t newcontent +=re.eduvideos[i].videotitle;\r\n");
      out.write("\t\t\t\t\t newcontent +='</strong>&nbsp;&nbsp;&nbsp;&nbsp;<font color=\"#999999\">';\r\n");
      out.write("\t\t\t\t\t newcontent +=re.eduvideos[i].videoreleasetime;\r\n");
      out.write("\t\t\t\t\t newcontent +='</font></p><p>';\r\n");
      out.write("\t\t\t\t\t newcontent +=re.eduvideos[i].content;\r\n");
      out.write("\t\t\t\t\t newcontent +='</p></td></tr></table></li>';\r\n");
      out.write("\t\t\t\t\t if(i==0)\r\n");
      out.write("\t\t\t\t\t {\r\n");
      out.write("\t\t\t\t\t \tloadRuleContent2(re.eduvideos[i].id);\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('#edulisthtml2').html(newcontent);\r\n");
      out.write("\t\t\t//var lidiv = {'self':'.limit','rate':35};$(document.body).limit(document.documentElement.clientWidth,lidiv);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\talert('ajax error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t// Replace old content with new content\r\n");
      out.write("\t\r\n");
      out.write("\t// Prevent click eventpropagation\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//右边页面显示栏  图文模块\r\n");
      out.write("function loadRuleContent2(id)\r\n");
      out.write("{\r\n");
      out.write("\t\tvar newcontent ='';\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',//可选get\r\n");
      out.write("\t\turl:'getEduDateinfo.action',//这里是接收数据的PHP程序\r\n");
      out.write("\t\tdata:'eduid='+id+'&random='+Math.random(),//传给PHP的数据，多个参数用&连接\r\n");
      out.write("\t\tdataType:'Json',//服务器返回的数据类型 可选XML ,Json jsonp script html text等\r\n");
      out.write("\t\tcontentType: \"application/x-www-form-urlencoded; charset=utf-8\", \r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t//这里是ajax提交成功后，PHP程序返回的数据处理函数。msg是返回的数据，数据类型在dataType参数里定义！\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar re =eval('('+elformat(data)+')');\r\n");
      out.write("\t\t\t\tnewcontent +='<p style=\"text-align:center;font:14px;\"><strong>'+re.videotitle+'</strong></p>';\r\n");
      out.write("\t\t\t\tnewcontent +='<p style=\"text-align:center;\">时间: '+re.videoreleasetime+'</p>';\r\n");
      out.write("\t\t\t\tnewcontent +='<p>'+(re.content == 'null' ? \"暂无详细内容\":re.content)+'</p>';\r\n");
      out.write("\t\t\t$('#contenthtml2').html(newcontent);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tautoscroll({'id':'jp-container2'});\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror:function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\talert('error');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// The form contains fields for many pagiantion optiosn so you can\r\n");
      out.write("// quickly see the resuluts of the different options.\r\n");
      out.write("// This function creates an option object for the pagination function.\r\n");
      out.write("// This will be be unnecessary in your application where you just set\r\n");
      out.write("// the options once.\r\n");
      out.write("function getOptionsFromForm(){\r\n");
      out.write("\tvar opt = {callback: pageselectCallback};\r\n");
      out.write("\t// Collect options from the text fields - the fields are named like their option counterparts\r\n");
      out.write("\t//\"Previous\" label\r\n");
      out.write("\topt.prev_text = '上一页';\r\n");
      out.write("\t//\"Next\" label\r\n");
      out.write("\topt.next_text = '下一页';\r\n");
      out.write("\t//Number of pagination links shown\r\n");
      out.write("\topt.num_display_entries = '3';\r\n");
      out.write("\t//Number of items per page\r\n");
      out.write("\topt.items_per_page = '4';\r\n");
      out.write("\t// Avoid html injections in this demo\r\n");
      out.write("\tvar htmlspecialchars ={ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\"};\r\n");
      out.write("\t$.each(htmlspecialchars, function(k,v){\r\n");
      out.write("\t\topt.prev_text = opt.prev_text.replace(k,v);\r\n");
      out.write("\t\topt.next_text = opt.next_text.replace(k,v);\r\n");
      out.write("\t})\r\n");
      out.write("\treturn opt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getOptionsFromForm2(){\r\n");
      out.write("\tvar opt = {callback: pageselectCallback2};\r\n");
      out.write("\t// Collect options from the text fields - the fields are named like their option counterparts\r\n");
      out.write("\t//\"Previous\" label\r\n");
      out.write("\topt.prev_text = '上一页';\r\n");
      out.write("\t//\"Next\" label\r\n");
      out.write("\topt.next_text = '下一页';\r\n");
      out.write("\t//Number of pagination links shown\r\n");
      out.write("\topt.num_display_entries = '3';\r\n");
      out.write("\t//Number of items per page\r\n");
      out.write("\topt.items_per_page = '4';\r\n");
      out.write("\t// Avoid html injections in this demo\r\n");
      out.write("\tvar htmlspecialchars ={ \"&\":\"&amp;\", \"<\":\"&lt;\", \">\":\"&gt;\", '\"':\"&quot;\"};\r\n");
      out.write("\t$.each(htmlspecialchars, function(k,v){\r\n");
      out.write("\t\topt.prev_text = opt.prev_text.replace(k,v);\r\n");
      out.write("\t\topt.next_text = opt.next_text.replace(k,v);\r\n");
      out.write("\t})\r\n");
      out.write("\treturn opt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function contentappend()\r\n");
      out.write("{\r\n");
      out.write("\tvar content = '<div id=\"jp-container\" class=\"jp-container autowidth\"><div style=\"padding:10px 15px; line-height:22px\" id=\"contenthtml\">';\r\n");
      out.write("\tcontent += $('#contenthtml').html();\r\n");
      out.write("\tcontent += '</div></div>';\r\n");
      out.write("\t\r\n");
      out.write("\t$('#contentdetail').html(content);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function contentappend2()\r\n");
      out.write("{\r\n");
      out.write("\tvar content = '<div id=\"jp-container2\" class=\"jp-container autowidth\"><div style=\"padding:10px 15px; line-height:22px\" id=\"contenthtml2\">';\r\n");
      out.write("\tcontent += $('#contenthtml2').html();\r\n");
      out.write("\tcontent += '</div></div>';\r\n");
      out.write("\t\r\n");
      out.write("\t$('#contentdetail2').html(content);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar optInit = getOptionsFromForm();\r\n");
      out.write("\tvar optInit2 = getOptionsFromForm2();\r\n");
      out.write("\t$(\"#Pagination\").pagination(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(", optInit);\r\n");
      out.write("\t$(\"#Pagination2\").pagination(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write(", optInit2);\r\n");
      out.write("\t\r\n");
      out.write("\t//自动适应屏幕宽度js\r\n");
      out.write("\tvar opt = {'widthname':'autowidth','callback':function(e){contentappend();contentappend2();autoscroll();autoscroll({'id':'jp-container2'})}};\r\n");
      out.write("\t\r\n");
      out.write("\topt = atuoscreen(opt);\r\n");
      out.write("\r\n");
      out.write("\t$(document).bind(\"keydown\",function(e){if(e.which == 122)flag=false;});\r\n");
      out.write("\twindow.onresize=function(){\r\n");
      out.write("\t\t\topt = atuoscreen(opt);\r\n");
      out.write("\t\t\tvar lidiv = {'self':'.limit','rate':51};$(document.body).limit(document.documentElement.clientWidth,lidiv);\r\n");
      out.write("\t};\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write(" var oMoveBox = $(\"#col_box\"), oArr = $(\"#arrow\"), maxL = 185;\r\n");
      out.write(" oArr.click(function(){\r\n");
      out.write("  oMoveBox.animate({\"height\":\"-=\"+maxL},185,function(){\r\n");
      out.write("   maxL = -maxL;\r\n");
      out.write("  $(\"#arrow\").html(maxL<0 ? \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\\\"></img>\" : \"<img src=\\\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk01.png\\\"></img>\");\r\n");
      out.write("  })\r\n");
      out.write(" });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"top\" id=\"box\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"col_box\">\r\n");
      out.write("<table width=\"100%\" height=\"108\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"float:left\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t<span class=\"padding-left \"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index_view.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/logo.png\" class=\"autoheight\" style=\"width:508px;height:104px;\" /></a></span>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td rowspan=\"2\" align=\"right\" valign=\"bottom\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/logo_img1.png\"/>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("    <td align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t<div style=\"padding:10px 10px 10px 15px;width:100%\">\r\n");
      out.write("\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t    <!--首页-->\r\n");
      out.write("\t\t\t    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/index_view.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav11.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t    <!--交通法规-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/rule_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav01.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--宣教中心-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/edu_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav02.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--基本信息-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/driver_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav03.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--违法查询-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/ruleIllegal_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav04.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--快速处理点-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/branch_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav05.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--安全提醒-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/safeNotice_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav06.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--会议通知-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/meetNotice_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav07.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--问题互动-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/interchange_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav08.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<!--微博微信-->\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/micromessage_list.action\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/nav09.png\" style=\"width:60px;height:60px;\" /></a>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--后台管理-->\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>\r\n");
      out.write("<!--<div id=\"arrow\">︿</div>-->\r\n");
      out.write("<div id=\"arrow\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/zk02.png\"> </img></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"clear\"></div>");
      out.write("\r\n");
      out.write("\t<div class=\"main\">\r\n");
      out.write("\t\t<div class=\"box\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"nTab\">\r\n");
      out.write("\t\t\t\t<!-- 标题开始 -->\r\n");
      out.write("\t\t\t\t<div class=\"TabTitle\">\r\n");
      out.write("\t\t\t\t\t<div class=\"jt_h3 pos\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"left main_left\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/icon02.png\" align=\"absmiddle\" />&nbsp;&nbsp;宣教中心</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"gb\"><a href=\"#\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/close.png\" width=\"10\" height=\"10\" /></a></span>\r\n");
      out.write("\t\t\t\t\t\t<ul id=\"myTab0\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\" onmouseover=\"nTabs(this,0);\">视频</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"normal\" onmouseover=\"nTabs(this,1);\">图文</li>\r\n");
      out.write("\t\t\t\t\t\t\t<!--<li class=\"normal\" onmouseover=\"nTabs(this,2);\">题库</li>-->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t<div class=\"TabContentny padding\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t<!--视频 -->\r\n");
      out.write("\t<div id=\"myTab0_Content0\">\r\n");
      out.write("\t\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t\t<td width=\"38%\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t   <div style=\"border:2px solid #D8DFEA;height:500px\">\r\n");
      out.write("\t\t\t  <ul class=\"ny_sp\" id='edulisthtml'>\r\n");
      out.write("\t\t\t  </ul>\r\n");
      out.write("\t\t\t  <div class=\"clear\"></div>\r\n");
      out.write("\t\t\t  <div class=\"sabrosus\"><div id='Pagination' class=\"pagination\"></div></div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t\t <td width=\"2%\">\r\n");
      out.write("\t\t    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/jt.gif\"></img>\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t\t <td align=\"left\" valign=\"top\" id=\"contentdetail\">\r\n");
      out.write("\t\t\t   <div id=\"jp-container\" class=\"jp-container autowidth\" >\r\n");
      out.write("\t\t\t       <div  id=\"contenthtml\">\r\n");
      out.write("\t\t\t       </div>\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 图文 -->\t\t\t\t\t\r\n");
      out.write("<div id=\"myTab0_Content1\" class=\"none\">\r\n");
      out.write("<div class=\"box_nr1  padding\">\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t\t<td width=\"38%\" align=\"left\" valign=\"top\">\r\n");
      out.write("\t\t  <div style=\"border:2px solid #D8DFEA;height:500px\">\r\n");
      out.write("\t\t\t   <ul class=\"ny_sp\" id='edulisthtml2'>\r\n");
      out.write("\t\t\t   </ul>\r\n");
      out.write("\t\t\t  <div class=\"clear\"></div>\r\n");
      out.write("\t\t\t  <div class=\"sabrosus\"><div id='Pagination2' class=\"pagination2\"></div></div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t     </td>\r\n");
      out.write("\t\t\t <td width=\"2%\">\r\n");
      out.write("\t\t\t\t\t\t  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectpath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/page/images/jt.gif\"></img>\r\n");
      out.write("\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t<td align=\"left\" valign=\"top\" id=\"contentdetail2\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"jp-container2\" class=\"jp-container autowidth\" >\r\n");
      out.write("\t\t\t<div style=\"padding:10px 15px; line-height:22px\" id=\"contenthtml2\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--试题-->\r\n");
      out.write("<div id=\"myTab0_Content2\" class=\"none\">3</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"color: #2a81c4; text-align: center\">版权所有：机动车网上交通安全宣传教育监控平台&nbsp;&nbsp;技术支持：浙江网泽</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
